name: hic2self_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - torchvision
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - coolbox
  - h5py
  - umap-learn
  - anndata
  - pip
  - pip:
    - pytorch-ssim
